controller_frequency: 5.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.05
  max_vel_theta: 2.0
  min_vel_theta: 0.5
  min_in_place_vel_theta: 0.5
  max_rotational_vel: 2.0
  min_in_place_rotational_vel: 0.5
  escape_vel: -0.10
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 2.0

  holonomic_robot: false
  yaw_goal_tolerance: 0.1 # about 6 degrees
  xy_goal_tolerance: 0.05 # 5 cm
  goal_distance_bias: 0.6
  path_distance_bias: 0.8

  heading_lookahead: 0.3
  meter_scoring: false
  heading_scoring: false
  heading_scoring_timestep: 0.1
  oscillation_reset_dist: 0.05
  occdist_scale: 0.05
  publish_cost_grid_pc: false

  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 8
  vtheta_samples: 20
  dwa: true
  simple_attractor: false
  
